version: "3.8"

services:
  api:
    build: .
    container_name: stock-index-api
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
